name: workers
module_class: app.ext.byzantium.Krok
description: a synode for page and component generation
instructions: optimize the page contents and aspects
triggers:
  - page,component
operators:
  - alias: DraphtBot
    operator_type: bot
    operator_path: app.ext.drapht.bots.draphtBot.DraphtBot
    handlers: [ ]
synode:
  - agent: page
    operator: DraphtBot
    store_key: wireframe
    instructions: |
      evaluate screen shot of page and optimize it, generate a wireframe for the $trigger with markdown language
  - agent: main
    operator: DraphtBot
    store_key: wireframe
    instructions: |
      evaluate screen shot of page and optimize it, generate a wireframe for the $trigger with markdown language

output:
  - $optimize.result
